# Generated by Django 5.2 on 2025-05-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("work", "На работе"),
                    ("vacation", "В отпуске"),
                    ("sick_leave", "На больничном"),
                    ("truancy", "Прогул"),
                ],
                default="work",
                null=True,
                verbose_name="Статус сотрудника",
            ),
        ),
    ]
