# Generated by Django 5.2 on 2025-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="times",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время исполнения"
            ),
        ),
    ]
