# Generated by Django 6.0.4 on 2026-04-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Признак активности"),
        ),
    ]
