# Generated by Django 6.0.4 on 2026-04-16 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_is_active"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                default="Не выбран",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="employees.employee",
                verbose_name="Исполнители",
            ),
        ),
    ]
