# Generated by Django 5.2 on 2025-05-03 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                default="Не выбран",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнители",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("start", "К исполнению"),
                    ("done", "Выполнена"),
                    ("free", "Свободна"),
                    ("closed", "Отменена"),
                ],
                default="Свободна",
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
