# Generated by Django 5.2 on 2025-05-17 05:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="employee",
        ),
        migrations.AddField(
            model_name="task",
            name="employee",
            field=models.ManyToManyField(
                blank=True,
                default="Не выбран",
                null=True,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнители",
            ),
        ),
    ]
