# Generated by Django 5.2 on 2025-05-17 05:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_remove_task_employee_task_employee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="employee",
            field=models.ManyToManyField(
                blank=True,
                default="Не выбран",
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнители",
            ),
        ),
    ]
