# Generated by Django 5.2 on 2025-05-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_task_employee_alter_task_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("start", "К исполнению"),
                    ("done", "Выполнена"),
                    ("free", "Свободна"),
                    ("closed", "Отменена"),
                ],
                default="free",
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
