# Generated by Django 5.2 on 2025-05-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("OGESh", "ОЭГШ"),
                            ("SB", "CБ"),
                            ("SIT", "СИТ"),
                            ("OGM", "ОГМ"),
                        ],
                        max_length=50,
                        verbose_name="Название Отдела",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отдел",
                "verbose_name_plural": "Отделы",
            },
        ),
    ]
